# -*- coding: utf-8 -*-
"""Fake News Data Sets

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAm5v_yZsr51fnE8QJy4TozC8Q3MeqMS

Data Sets

- https://github.com/KaiDMML/FakeNewsNet
 - News articles
 - Tweets
 - Retweets 
 - user_profile
 - user_timeline_tweets
 - user_followers
- https://paperswithcode.com/datasets?task=fake-news-detection
 - LIAR: 12.8K labelled statements from PolitiFact.com
 - RealNews: News Articles from common crawl, in the 5000 domains specificed by google news
 - FNC-1 stance detection data set: agree, disagree, discuss, unrelated
 - Covid-19 Fake News Data Set
 - NELA - GT - 2018, 2019, 2020: truth ratings based on dimensions like reliability, bias, transparency, adherence to journalistic standards and consumer trust
- https://data.4tu.nl/articles/dataset/Repository_of_fake_news_detection_datasets/14151755
  - Contains 27 freely available datasets with 11 features each 
- https://www.kaggle.com/ssismasterchief/machine-hack-fake-news-content-detection
 - Another Kaggle dataset
- https://ieee-dataport.org/keywords/fake-news
 - Another Covid fake news data set
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8237334/
 - Comparision of fake news data sets
- https://github.com/joolsa/fake_real_news_dataset
 - 11,000 articles tagged as fake or real
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
pd.plotting.register_matplotlib_converters() 
import matplotlib.pyplot as plt 
# %matplotlib inline 
import seaborn as sns

# KaiDMML Investigation

# Papers with Code

# Repository of Fake News Detection

# Covid Fake News Data sets

# Kaggle

# Other